# baseURL: https://atlantacfi.co/
languageCode: en-us
title: Tim Cailloux (Atlanta CFI)
theme: "PaperMod"

assets:
    favicon: "/favicon/favicon.ico"
    favicon16x16:  "/favicon/favicon-16x16.png"
    favicon32x32:  "/favicon/favicon-32x32.png"
    apple_touch_icon:  "/favicon/apple-touch-icon.png"
    safari_pinned_tab:  "/favicon/safari-pinned-tab.svg"

params:
  defaultTheme: light
  disableThemeToggle: true
  ShowShareButton: true
  ShowReadingTime: true
  profileMode:
    enabled: true
    title: "Tim Cailloux"
    subtitle: "Atlanta-area Flight Instruction"
    imageUrl: /img/intro_icon.png
    # imageWidth: 120 # custom size
    # imageHeight: 120 # custom size
    buttons:
      - name: Schedule
        url: "/scheduling"
      - name: About
        url: "/about"


enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: scheduling
      name: Scheduling
      url: /scheduling/
      weight: 20
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary