baseURL: https://atlantacfi.co/
languageCode: en-us
title: Tim Cailloux (Atlanta CFI)
theme: "PaperMod"

enableRobotsTXT: true

params:
  defaultTheme: light
  ShowBreadCrumbs: true
  disableThemeToggle: true
  ShowShareButton: true
  ShowReadingTime: true
  label:
    text: "Tim Cailloux, CFI"
    icon: "/img/intro_icon.png"
  profileMode:
    enabled: true
    title: "Tim Cailloux"
    subtitle: "Atlanta-area Flight Instruction, based at PDK and FFC"
    imageUrl: /img/tim_headshot.jpeg
    # imageWidth: 120 # custom size
    # imageHeight: 120 # custom size
    buttons:
      - name: Schedule
        url: "/scheduling"
      - name: About
        url: "/about"
      - name: Rusty Pilot
        url: "/rustypilot"
  
  socialIcons:
    - name: "instagram"
      url: "https://www.instagram.com/i_fly_ifr/"
    - name: "github"
      url: "https://github.com/cailloux"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/tcailloux/"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: about
      name: About
      pageRef: /about
      weight: 20
    - identifier: scheduling
      name: Scheduling
      pageRef: /scheduling
      weight: 30
    - identifier: posts
      name: Posts
      pageRef: /posts
      weight: 40
    - identifier: lessons
      name: Lesson Plans
      pageRef: /lessons/
      weight: 50
    - identifier: search
      name: Search
      pageRef: /search
      weight: 60

googleAnalytics: "G-MWEKFMQ43C"

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary