# baseURL: https://atlantacfi.co/
languageCode: en-us
title: Tim Cailloux (Atlanta CFI)
theme: "PaperMod"

params:
  defaultTheme: light
  disableThemeToggle: true
  ShowShareButton: true
  ShowReadingTime: true
  profileMode:
    enabled: true
    title: "Tim Cailloux"
    subtitle: "Atlanta-area Flight Instruction, based at PDK and FFC"
    imageUrl: /img/intro_icon.png
    # imageWidth: 120 # custom size
    # imageHeight: 120 # custom size
    buttons:
      - name: Schedule
        url: "/scheduling"
      - name: About
        url: "/about"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 20
    - identifier: scheduling
      name: Scheduling
      url: /scheduling/
      weight: 30
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 40
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 50
    - identifier: search
      name: Search
      url: /search/
      weight: 60

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary