# Configure Cloudflare Worker

name = "atlantacfi"
compatibility_date = "2025-08-20"

[build]
command = "chmod a+x build.sh && ./build.sh"

[assets]
not_found_handling = "404-page"
directory = "./public"
