# Configure Cloudflare Worker

name = "atlanta-cfi"
compatibility_date = "2025-08-20"

[build]
command = "chmod a+x build.sh && ./build.sh"

[assets]
pages_build_output_dir = "./public"
not_found_handling = "404-page"
